### ISSUE TITLE
Feature Request: frozen columns

### ISSUE THREAD

**Issue by jahglow** [customelements/customelements.io#524]
The only reason that prevents me from vaadin-grid to using this awesome table is the lack of abiility to pin n-columns from scrolling (fro instance two first columns if frozen do not scroll whereas others scroll). That'd have become a killer-feature. Any plans implementing that one?

**Comment by zenorocha** [comment]
You should fill an issue with Vaadin ;) https://github.com/vaadin/vaadin-grid

**Comment by jahglow** [comment]
No, probably I worded this incorrectly. The only reason that prevents me switching from vaadin to your element is that your element desn't support freezing columns which is a musthave feature for mobile and tables. And I really hate the way vaadin does polymer in their grid. Is there freezing columns somewhere on your roadmap?

**Comment by zenorocha** [comment]
You're filling the issue on the wrong place.

**Comment by jahglow** [comment]
you're damn right)
